import os
from sqlalchemy import create_engine, Column, Integer, String, Boolean, Text, DateTime, JSON, ForeignKey
from sqlalchemy.orm import declarative_base, sessionmaker, relationship
from datetime import datetime

Base = declarative_base()

class Community(Base):
    """
    Stores data about discovered and managed Egyptian communities.
    """
    __tablename__ = 'communities'
    
    id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False)
    platform = Column(String(50), nullable=False) # e.g., 'Facebook Group', 'WhatsApp Community'
    url = Column(String(500), unique=True)
    governorate = Column(String(100)) # e.g., 'Cairo', 'Alexandria', 'All'
    audience_demographics = Column(JSON)
    audience_size = Column(Integer)
    main_topics = Column(String(500))
    language_preference = Column(String(50), default='Egyptian Arabic')
    posting_restrictions = Column(Text)
    moderation_strictness = Column(String(50)) # 'Low', 'Medium', 'High'
    promotional_allowed = Column(Boolean, default=False)
    status = Column(String(50), default='Needs Review') # 'Approved', 'Needs Review', 'Prohibited'
    
    posts = relationship('Post', back_populates='community')

class Campaign(Base):
    """
    Mirror of active campaigns fetched from ERPNext to guide the Content Crew.
    """
    __tablename__ = 'campaigns'
    
    id = Column(Integer, primary_key=True)
    erpnext_campaign_id = Column(String(255), unique=True)
    name = Column(String(255), nullable=False)
    objectives = Column(Text)
    target_governorates = Column(JSON)
    budget = Column(String(100))
    start_date = Column(DateTime)
    end_date = Column(DateTime)
    status = Column(String(50), default='Active')

class Post(Base):
    """
    Drafted and Published content generated by the AI for specific communities.
    """
    __tablename__ = 'posts'
    
    id = Column(Integer, primary_key=True)
    campaign_id = Column(Integer, ForeignKey('campaigns.id'))
    community_id = Column(Integer, ForeignKey('communities.id'))
    
    content = Column(Text, nullable=False)
    language = Column(String(50))
    
    # Media URLs generated by the Media Agent
    image_url = Column(String(500))
    video_url = Column(String(500))
    media_recommendations = Column(JSON) # Fallback for detailed instructions
    
    status = Column(String(50), default='Needs Approval') # 'Needs Approval', 'Approved', 'Published', 'Rejected'
    published_url = Column(String(500))
    published_at = Column(DateTime)
    
    community = relationship('Community', back_populates='posts')
    campaign = relationship('Campaign')

class EngagementLog(Base):
    """
    Stores metrics and responses generated by the Interaction Agent.
    """
    __tablename__ = 'engagement_logs'
    
    id = Column(Integer, primary_key=True)
    post_id = Column(Integer, ForeignKey('posts.id'))
    platform_post_id = Column(String(255))
    metrics = Column(JSON) # e.g., {'likes': 100, 'comments': 20}
    timestamp = Column(DateTime, default=datetime.utcnow)

def init_db(database_url: str):
    """Initializes the standalone SQL database."""
    engine = create_engine(database_url)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    return Session()

if __name__ == "__main__":
    # Example usage for testing schema creation
    from dotenv import load_dotenv
    load_dotenv()
    db_url = os.getenv("DATABASE_URL", "sqlite:///growth_specialist.db")
    session = init_db(db_url)
    print(f"Database initialized at {db_url}")
